### ISSUE TITLE
[FE] Milestone 설정 tab 구현

### ISSUE THREAD

**Issue by Yejikwon** [boostcamp-2020/IssueTracker-08#116]
## 🔍 Feature
 
| Name             | about | title | labels | assignees |
| ---------------- | -------- | -------- | -------- | -------- |
| Feature Request  | Suggest an idea for this project  |   |    |    |

---

## 🗣 설명
Milestone 설정 tab 구현
<br/>

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트
- [ ] 마일스톤 목록 팝업
- [ ] Default: None milestone
- [ ] 어떤 마일스톤이 선택됐는지 확인 가능
<br/>

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항
<br/><br/>
